// Copyright 2026 Bitwise Media Group Ltd.
// SPDX-License-Identifier: MIT

package allowlist

import (
	"fmt"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/bitwise-media-group/patchy/internal/mirror/spec"
)

// Render produces the generated allowlist file: license header, GENERATED
// banner, the manifest's preamble as comments, then the entries. expired_at
// is always double-quoted, matching the hand-written allowlists' style so a
// chart opting in produces no gratuitous diff.
func Render(entries []spec.AllowlistEntry, preamble string) []byte {
	var b strings.Builder
	b.WriteString("# GENERATED by patchy mirror — do not hand-edit the entries.\n")
	b.WriteString("# Regenerated by `patchy mirror upgrade` from a fresh scan of the locked images:\n")
	b.WriteString("# findings that no longer appear are dropped, surviving entries keep their\n")
	b.WriteString("# original expired_at, and per-entry notes are preserved. Whole-file context\n")
	b.WriteString("# lives in scan.allowlist.preamble in manifest.yaml; per-finding analysis goes\n")
	b.WriteString("# in a \"notes\" field on the entry.\n")
	if preamble != "" {
		b.WriteString("#\n")
		for line := range strings.SplitSeq(strings.TrimRight(preamble, "\n"), "\n") {
			if line == "" {
				b.WriteString("#\n")
			} else {
				b.WriteString("# ")
				b.WriteString(line)
				b.WriteString("\n")
			}
		}
	}
	if len(entries) == 0 {
		b.WriteString("vulnerabilities: []\n")
		return []byte(b.String())
	}
	b.WriteString("vulnerabilities:\n")
	for _, e := range entries {
		writeField(&b, "  - ", "id", e.ID)
		writeField(&b, "    ", "statement", e.Statement)
		fmt.Fprintf(&b, "    expired_at: %q\n", e.ExpiredAt)
		if e.Notes != "" {
			writeField(&b, "    ", "notes", e.Notes)
		}
	}
	return []byte(b.String())
}

// writeField emits one key/value line, encoding the value the way a YAML
// encoder would (plain where safe, quoted or block otherwise).
func writeField(b *strings.Builder, prefix, key, value string) {
	enc := encodeScalar(value, prefix)
	fmt.Fprintf(b, "%s%s: %s\n", prefix, key, enc)
}

// encodeScalar renders value as a YAML scalar for an inline position at the
// given indentation. Single-line output splices after "key: "; multi-line
// values become an indented block scalar.
func encodeScalar(value, prefix string) string {
	raw, err := yaml.Marshal(value)
	if err != nil {
		// Marshal of a string cannot fail; quote defensively.
		return fmt.Sprintf("%q", value)
	}
	enc := strings.TrimRight(string(raw), "\n")
	if !strings.Contains(enc, "\n") {
		return enc
	}
	// Block scalar: re-base the encoder's fixed 4-space content indent to
	// two deeper than the key.
	indent := strings.Repeat(" ", len(prefix)+2)
	lines := strings.Split(enc, "\n")
	for i := 1; i < len(lines); i++ {
		lines[i] = indent + strings.TrimPrefix(lines[i], "    ")
	}
	return strings.Join(lines, "\n")
}
