// Copyright 2026 Bitwise Media Group Ltd.
// SPDX-License-Identifier: MIT

package spec

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// ImagesLock is a chart entry's images.lock.yaml: the pinned facts derived
// from the manifest — the upstream tgz digest and every referenced image
// resolved to a digest. Regenerated by machine; validate byte-compares it.
type ImagesLock struct {
	Chart  LockChart   `yaml:"chart"`
	Images []LockImage `yaml:"images"`
}

// LockChart records the vendored chart identity and its upstream tgz digest
// (the publish-time mutation tripwire).
type LockChart struct {
	Name              string `yaml:"name"`
	Version           string `yaml:"version"`
	UpstreamTgzSha256 string `yaml:"upstreamTgzSha256"`
}

// LockImage is one image pinned by digest, with its mirror targets.
type LockImage struct {
	// Source is the canonical upstream reference (normalized, tagged).
	Source string `yaml:"source"`
	// Digest is the manifest digest Source resolved to.
	Digest string `yaml:"digest"`
	// Targets maps each configured registry's name to the mirror reference
	// the image publishes to there.
	Targets map[string]string `yaml:"targets"`
	// Platforms lists os/arch pairs of a manifest list (empty for
	// single-platform images).
	Platforms []string `yaml:"platforms"`
}

// ArtifactLock is an artifact entry's lock.yaml.
type ArtifactLock struct {
	Artifact LockArtifact `yaml:"artifact"`
}

// LockArtifact pins one mirrored OCI artifact by digest.
type LockArtifact struct {
	// Ref is the canonical upstream repository (no tag).
	Ref string `yaml:"ref"`
	// Version is the pinned tag.
	Version string `yaml:"version"`
	// Digest is the manifest digest Ref:Version resolved to.
	Digest string `yaml:"digest"`
	// Targets maps each configured registry's name to the mirror reference
	// the artifact publishes to there.
	Targets map[string]string `yaml:"targets"`
	// Platforms lists os/arch pairs of a manifest list.
	Platforms []string `yaml:"platforms"`
}

// LoadImagesLock reads a chart lock file.
func LoadImagesLock(path string) (*ImagesLock, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var l ImagesLock
	if err := decodeStrict(raw, &l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, legacyLockHint(err))
	}
	return &l, nil
}

// LoadArtifactLock reads an artifact lock file.
func LoadArtifactLock(path string) (*ArtifactLock, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var l ArtifactLock
	if err := decodeStrict(raw, &l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, legacyLockHint(err))
	}
	return &l, nil
}

// legacyLockHint annotates a strict-decode failure over the pre-registries
// singular `target` field with the way out.
func legacyLockHint(err error) error {
	if strings.Contains(err.Error(), "field target not found") {
		return fmt.Errorf("%w (lock predates the multi-registry schema; "+
			"run 'patchy mirror upgrade' to regenerate it)", err)
	}
	return err
}

// Encode renders the lock in its canonical byte form. The shape is fixed,
// so the emitter is hand-rolled: a generic YAML encoder would not reproduce
// the committed files byte-for-byte, and the validate gate compares bytes.
func (l *ImagesLock) Encode() []byte {
	var b strings.Builder
	b.WriteString("chart:\n")
	fmt.Fprintf(&b, "  name: %s\n", l.Chart.Name)
	fmt.Fprintf(&b, "  version: %s\n", l.Chart.Version)
	fmt.Fprintf(&b, "  upstreamTgzSha256: %s\n", l.Chart.UpstreamTgzSha256)
	if len(l.Images) == 0 {
		b.WriteString("images: []\n")
		return []byte(b.String())
	}
	b.WriteString("images:\n")
	for _, img := range l.Images {
		fmt.Fprintf(&b, "  - source: %s\n", img.Source)
		fmt.Fprintf(&b, "    digest: %s\n", img.Digest)
		b.WriteString("    targets:\n")
		for _, name := range sortedKeys(img.Targets) {
			fmt.Fprintf(&b, "      %s: %s\n", name, img.Targets[name])
		}
		fmt.Fprintf(&b, "    platforms: %s\n", flowList(img.Platforms))
	}
	return []byte(b.String())
}

// Encode renders the lock in its canonical byte form.
func (l *ArtifactLock) Encode() []byte {
	var b strings.Builder
	b.WriteString("artifact:\n")
	fmt.Fprintf(&b, "  ref: %s\n", l.Artifact.Ref)
	fmt.Fprintf(&b, "  version: %s\n", l.Artifact.Version)
	fmt.Fprintf(&b, "  digest: %s\n", l.Artifact.Digest)
	b.WriteString("  targets:\n")
	for _, name := range sortedKeys(l.Artifact.Targets) {
		fmt.Fprintf(&b, "    %s: %s\n", name, l.Artifact.Targets[name])
	}
	fmt.Fprintf(&b, "  platforms: %s\n", flowList(l.Artifact.Platforms))
	return []byte(b.String())
}

// sortedKeys orders a targets map by registry name so the emitted bytes are
// insensitive to mirror.yaml reordering.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// flowList renders a string list in flow style with double-quoted items:
// ["a", "b"]. Matches the committed lock files' platform lists.
func flowList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
