// Copyright 2026 Bitwise Media Group Ltd.
// SPDX-License-Identifier: MIT

package spec

import (
	"fmt"
	"os"
	"strings"
)

// ChartManifest is a charts/<name>/manifest.yaml: the reviewed intent for
// one mirrored helm chart. Everything derived from it (the vendored tree,
// the rendered manifests, the images lock) is fact, regenerated by machine.
type ChartManifest struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	// Name must match the entry's directory name.
	Name      string        `yaml:"name"`
	Chart     ChartSpec     `yaml:"chart"`
	Discovery Discovery     `yaml:"discovery"`
	Images    Images        `yaml:"images"`
	OCIRefs   OCIRefs       `yaml:"ociRefs"`
	Scan      *ScanOverride `yaml:"scan"`
	Publish   ChartPublish  `yaml:"publish"`
}

// ChartSpec pins the upstream chart.
type ChartSpec struct {
	// Repo is the upstream chart location: an oci:// registry path or an
	// https:// helm repository (index.yaml).
	Repo string `yaml:"repo"`
	Name string `yaml:"name"`
	// Lockstep names an update group: entries sharing a lockstep value
	// ride one upstream version stream and must bump together in one PR
	// (a half-merged pair publishes an operator referencing images the
	// mirror doesn't carry yet). The group target is the LOWEST of the
	// members' newest satisfying versions, holding the bump until every
	// member carries the tag.
	Lockstep string `yaml:"lockstep"`
	// Version is the pinned upstream version; upgrade splices it.
	Version string `yaml:"version"`
	// VersionConstraint bounds what upgrade may pick (default: none).
	VersionConstraint string `yaml:"versionConstraint"`
	// VerifyUpstream declares the chart's upstream provenance
	// (provider none documents a gap).
	VerifyUpstream VerifyRule `yaml:"verifyUpstream"`
}

// Discovery configures the render that image discovery runs against.
type Discovery struct {
	// Namespace to render into (default: the entry name).
	Namespace string `yaml:"namespace"`
	// ValuesFiles are paths relative to the entry directory.
	ValuesFiles []string `yaml:"valuesFiles"`
	// KubeVersion is the Kubernetes version to render for (default 1.34.0).
	KubeVersion string `yaml:"kubeVersion"`
	// APIVersions are extra .Capabilities.APIVersions entries.
	APIVersions []string `yaml:"apiVersions"`
}

// defaultKubeVersion is the render target when discovery declares none.
const defaultKubeVersion = "1.34.0"

// EffectiveNamespace resolves the namespace default (the entry name).
func (d Discovery) EffectiveNamespace(entryName string) string {
	if d.Namespace != "" {
		return d.Namespace
	}
	return entryName
}

// EffectiveKubeVersion resolves the kube-version default.
func (d Discovery) EffectiveKubeVersion() string {
	if d.KubeVersion != "" {
		return d.KubeVersion
	}
	return defaultKubeVersion
}

// Images configures image discovery, tracking and upstream verification.
type Images struct {
	// Track re-picks tags for images on a release train of their own,
	// writing the pick into a values file. Wall-clock dependent: only
	// upgrade re-picks; every other stage uses the committed pin.
	Track []Track `yaml:"track"`
	// DistributionManifests derives extra images from a distribution
	// manifests artifact into the generated images.extra.yaml sidecar.
	DistributionManifests *DistributionManifests `yaml:"distributionManifests"`
	// Extra adds images helm rendering cannot see. {appVersion} expands
	// from the vendored Chart.yaml.
	Extra []ExtraImage `yaml:"extra"`
	// Exclude drops discovered references matching a glob pattern.
	Exclude []ExcludePattern `yaml:"exclude"`
	// AllowEmpty accepts a chart that renders no images (CRD-only charts).
	AllowEmpty bool `yaml:"allowEmpty"`
	// VerifyUpstream rules gate every locked image: first match wins, and
	// every image must match one (provider none documents a gap).
	VerifyUpstream []ImageVerifyRule `yaml:"verifyUpstream"`
}

// Track is one tracked image: the tag is machine-picked into a values file,
// so the rule names both an image and a path that must already resolve there
// — the pick replaces a value, it never invents one. The value there is
// either a full image reference (the pick replaces image:tag) or a bare
// tag for charts that split image.repository from image.tag (the pick
// replaces just the tag).
type Track struct {
	Image string `yaml:"image"`
	// VersionConstraint bounds the pick; empty derives the pinned tag's
	// own release train (">=<pin> <<major+1>.0.0"), so picks follow the
	// current major and never hop one on their own.
	VersionConstraint string `yaml:"versionConstraint"`
	// CooldownDays overrides the global soak for this image; 0 disables
	// the soak for an image that should track head.
	CooldownDays *int `yaml:"cooldownDays"`
	// ValuesFile defaults to the first discovery.valuesFiles entry.
	ValuesFile string `yaml:"valuesFile"`
	ValuesPath string `yaml:"valuesPath"`
}

// DistributionManifests configures sidecar derivation for charts whose
// workload images are deployed by an operator from manifests helm never
// renders (so discovery cannot see them).
type DistributionManifests struct {
	// Artifact is the manifests artifact ref; {appVersion} expands from
	// the vendored Chart.yaml.
	Artifact string `yaml:"artifact"`
	// Components name the manifest files whose Deployment images are
	// derived.
	Components []string `yaml:"components"`
	// Registry prefixes registry-less image references found in the
	// manifests (default ghcr.io) — the deploying operator prefixes its
	// configured registry the same way.
	Registry string `yaml:"registry"`
}

// ExtraImage adds one image with the reason it is invisible to discovery.
type ExtraImage struct {
	Image  string `yaml:"image"`
	Reason string `yaml:"reason"`
}

// ExcludePattern drops discovered references matching a glob.
type ExcludePattern struct {
	Pattern string `yaml:"pattern"`
}

// VerifyRule declares upstream provenance for a chart, artifact or image.
type VerifyRule struct {
	// Provider is none (documented gap), cosign-keyless or cosign-key.
	Provider string `yaml:"provider"`
	// CertificateIdentityRegexp is required for cosign-keyless.
	CertificateIdentityRegexp string `yaml:"certificateIdentityRegexp"`
	// CertificateOidcIssuer defaults to the GitHub Actions issuer.
	CertificateOidcIssuer string `yaml:"certificateOidcIssuer"`
	// Key is required for cosign-key: a URL or path to the public key.
	Key string `yaml:"key"`
	// SignatureDigestAlgorithm overrides the payload digest for
	// cosign-key publishers signing with a non-default one (sha512).
	SignatureDigestAlgorithm string `yaml:"signatureDigestAlgorithm"`
	// SignatureRepository is where signatures live when the publisher
	// stores them in a dedicated repository instead of alongside the
	// artifact.
	SignatureRepository string `yaml:"signatureRepository"`
}

// defaultOidcIssuer is the issuer assumed when a keyless rule names none.
const defaultOidcIssuer = "https://token.actions.githubusercontent.com"

// EffectiveOidcIssuer resolves the issuer default.
func (r VerifyRule) EffectiveOidcIssuer() string {
	if r.CertificateOidcIssuer != "" {
		return r.CertificateOidcIssuer
	}
	return defaultOidcIssuer
}

// EffectiveProvider resolves the provider default (none).
func (r VerifyRule) EffectiveProvider() string {
	if r.Provider == "" {
		return "none"
	}
	return r.Provider
}

// ImageVerifyRule is a VerifyRule scoped to images matching a glob.
type ImageVerifyRule struct {
	// Match is a glob over canonical source references.
	Match      string `yaml:"match"`
	VerifyRule `yaml:",inline"`
}

// OCIRefs governs oci:// references surviving in rendered output: anything
// outside the mirror bypasses the review gate and needs a reasoned
// allowance.
type OCIRefs struct {
	Allow []OCIRefAllow `yaml:"allow"`
}

// OCIRefAllow permits one non-mirror oci:// reference pattern, with the
// reason it may bypass the mirror.
type OCIRefAllow struct {
	Pattern string `yaml:"pattern"`
	Reason  string `yaml:"reason"`
}

// ScanOverride adjusts the global scan policy for one entry.
type ScanOverride struct {
	FailOn        []string        `yaml:"failOn"`
	IgnoreUnfixed *bool           `yaml:"ignoreUnfixed"`
	Allowlist     AllowlistPolicy `yaml:"allowlist"`
}

// AllowlistPolicy opts an entry into allowlist derivation.
type AllowlistPolicy struct {
	// Generate regenerates security/allowlist.yaml from the scan during
	// upgrade; the PR review is where the risk is actually accepted.
	Generate bool `yaml:"generate"`
	// Preamble is whole-file context rendered as comments atop the
	// generated allowlist.
	Preamble string `yaml:"preamble"`
}

// ChartPublish names the publish destination.
type ChartPublish struct {
	// ChartRepo is the repository path applied under every registry URL
	// (default <chartNamespace>/<name>).
	ChartRepo string `yaml:"chartRepo"`
}

// ScanPolicy is the resolved (entry over global) blocking policy.
type ScanPolicy struct {
	FailOn        []string
	IgnoreUnfixed bool
}

// EffectiveScanPolicy resolves an entry's scan override against the global
// scan config.
func EffectiveScanPolicy(global Scan, override *ScanOverride) ScanPolicy {
	p := ScanPolicy{FailOn: global.EffectiveFailOn(), IgnoreUnfixed: global.EffectiveIgnoreUnfixed()}
	if override != nil {
		if len(override.FailOn) > 0 {
			p.FailOn = override.FailOn
		}
		if override.IgnoreUnfixed != nil {
			p.IgnoreUnfixed = *override.IgnoreUnfixed
		}
	}
	return p
}

// ArtifactManifest is an artifacts/<name>/manifest.yaml: one mirrored OCI
// artifact that is not a helm chart (a manifests bundle, a policy bundle,
// a standalone image).
type ArtifactManifest struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	// Name must match the entry's directory name.
	Name     string          `yaml:"name"`
	Artifact ArtifactSpec    `yaml:"artifact"`
	Scan     ArtifactScan    `yaml:"scan"`
	Publish  ArtifactPublish `yaml:"publish"`
}

// ArtifactSpec pins the upstream artifact.
type ArtifactSpec struct {
	// Ref is the upstream repository (no tag): e.g. ghcr.io/acme/bundles.
	Ref string `yaml:"ref"`
	// Version is the pinned tag; upgrade splices it.
	Version string `yaml:"version"`
	// VersionConstraint bounds what upgrade may pick.
	VersionConstraint string `yaml:"versionConstraint"`
	// CooldownDays applies the tracked-tag soak to version picks
	// (default: the global cooldown).
	CooldownDays *int `yaml:"cooldownDays"`
	// Lockstep names an update group, as for charts.
	Lockstep string `yaml:"lockstep"`
	// VerifyUpstream declares the artifact's upstream provenance.
	VerifyUpstream VerifyRule `yaml:"verifyUpstream"`
}

// ArtifactScan opts the artifact into image scanning.
type ArtifactScan struct {
	// Enabled is auto (scan iff the artifact is a runnable image), true
	// or false.
	Enabled string `yaml:"enabled"`
}

// EffectiveEnabled resolves the enabled default (auto).
func (s ArtifactScan) EffectiveEnabled() string {
	if s.Enabled == "" {
		return "auto"
	}
	return s.Enabled
}

// ArtifactPublish names the publish destination.
type ArtifactPublish struct {
	// Repo is the repository path applied under every registry URL
	// (default <artifactNamespace>/<canonical source path>).
	Repo string `yaml:"repo"`
}

// legacySigningHint annotates a strict-decode failure over the removed
// per-entry `signing` block with the way out.
func legacySigningHint(err error) error {
	if strings.Contains(err.Error(), "field signing not found") {
		return fmt.Errorf("%w (per-entry signing was replaced by per-registry "+
			"signing blocks in mirror.yaml; move the override there)", err)
	}
	return err
}

// LoadChartManifest reads and validates a chart manifest.
func LoadChartManifest(path string) (*ChartManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var m ChartManifest
	if err := decodeStrict(raw, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, legacySigningHint(err))
	}
	if err := checkHeader(m.APIVersion, m.Kind, KindChart); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}

// LoadArtifactManifest reads and validates an artifact manifest.
func LoadArtifactManifest(path string) (*ArtifactManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var m ArtifactManifest
	if err := decodeStrict(raw, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, legacySigningHint(err))
	}
	if err := checkHeader(m.APIVersion, m.Kind, KindArtifact); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}
