// Copyright 2026 Bitwise Media Group Ltd.
// SPDX-License-Identifier: MIT

package spec

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// SidecarFile is the generated extra-images sidecar, relative to an entry
// directory. Machine-derived extras (distribution manifests) land here and
// are merged during discovery, so manifest.yaml stays a pure intent file
// that no machine ever rewrites.
const SidecarFile = "images.extra.yaml"

// Sidecar is a generated images.extra.yaml.
type Sidecar struct {
	Extra []ExtraImage `yaml:"extra"`
}

// LoadSidecar reads an entry's generated sidecar. A missing file is an
// empty sidecar, not an error.
func LoadSidecar(entryDir string) (*Sidecar, error) {
	path := filepath.Join(entryDir, SidecarFile)
	raw, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return &Sidecar{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var s Sidecar
	if err := decodeStrict(raw, &s); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &s, nil
}

// Encode renders the sidecar in its canonical byte form, GENERATED header
// included.
func (s *Sidecar) Encode() []byte {
	var b strings.Builder
	b.WriteString("# GENERATED by patchy mirror — do not hand-edit.\n")
	b.WriteString("# Extra images derived from the entry's distribution manifests artifact;\n")
	b.WriteString("# regenerated by `patchy mirror upgrade` and merged during image discovery.\n")
	if len(s.Extra) == 0 {
		b.WriteString("extra: []\n")
		return []byte(b.String())
	}
	b.WriteString("extra:\n")
	for _, e := range s.Extra {
		fmt.Fprintf(&b, "  - image: %s\n", e.Image)
		fmt.Fprintf(&b, "    reason: %s\n", e.Reason)
	}
	return []byte(b.String())
}
